name: opus_dart
version: 3.0.1
homepage: https://github.com/EPNW/opus_dart
description: Wraps libopus in dart, and additionally provides a dart friendly API for encoding and decoding
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  ffi: ^2.1.3
  wasm_ffi: ^2.0.7
